//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FGA_PLATFORM.PLEXSOAP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://www.plexus-online.com/DataSource")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Parameter))]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteDataSourceOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteDataSourceByDataSourceKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataSourceRequestTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback ExecuteDataSourcePostOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::FGA_PLATFORM.Properties.Settings.Default.FGA_PLATFORM_PLEXSOAP_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteDataSourceCompletedEventHandler ExecuteDataSourceCompleted;
        
        /// <remarks/>
        public event ExecuteDataSourceByDataSourceKeyCompletedEventHandler ExecuteDataSourceByDataSourceKeyCompleted;
        
        /// <remarks/>
        public event GetDataSourceRequestTemplateCompletedEventHandler GetDataSourceRequestTemplateCompleted;
        
        /// <remarks/>
        public event ExecuteDataSourcePostCompletedEventHandler ExecuteDataSourcePostCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plexus-online.com/DataSource/ExecuteDataSource", RequestNamespace="http://www.plexus-online.com/DataSource", ResponseNamespace="http://www.plexus-online.com/DataSource", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecuteDataSourceResult ExecuteDataSource(ExecuteDataSourceRequest ExecuteDataSourceRequest) {
            object[] results = this.Invoke("ExecuteDataSource", new object[] {
                        ExecuteDataSourceRequest});
            return ((ExecuteDataSourceResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataSourceAsync(ExecuteDataSourceRequest ExecuteDataSourceRequest) {
            this.ExecuteDataSourceAsync(ExecuteDataSourceRequest, null);
        }
        
        /// <remarks/>
        public void ExecuteDataSourceAsync(ExecuteDataSourceRequest ExecuteDataSourceRequest, object userState) {
            if ((this.ExecuteDataSourceOperationCompleted == null)) {
                this.ExecuteDataSourceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataSourceOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataSource", new object[] {
                        ExecuteDataSourceRequest}, this.ExecuteDataSourceOperationCompleted, userState);
        }
        
        private void OnExecuteDataSourceOperationCompleted(object arg) {
            if ((this.ExecuteDataSourceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataSourceCompleted(this, new ExecuteDataSourceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plexus-online.com/DataSource/ExecuteDataSourceByDataSourceKey", RequestNamespace="http://www.plexus-online.com/DataSource", ResponseNamespace="http://www.plexus-online.com/DataSource", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecuteDataSourceResult ExecuteDataSourceByDataSourceKey(int dataSourceKey) {
            object[] results = this.Invoke("ExecuteDataSourceByDataSourceKey", new object[] {
                        dataSourceKey});
            return ((ExecuteDataSourceResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataSourceByDataSourceKeyAsync(int dataSourceKey) {
            this.ExecuteDataSourceByDataSourceKeyAsync(dataSourceKey, null);
        }
        
        /// <remarks/>
        public void ExecuteDataSourceByDataSourceKeyAsync(int dataSourceKey, object userState) {
            if ((this.ExecuteDataSourceByDataSourceKeyOperationCompleted == null)) {
                this.ExecuteDataSourceByDataSourceKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataSourceByDataSourceKeyOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataSourceByDataSourceKey", new object[] {
                        dataSourceKey}, this.ExecuteDataSourceByDataSourceKeyOperationCompleted, userState);
        }
        
        private void OnExecuteDataSourceByDataSourceKeyOperationCompleted(object arg) {
            if ((this.ExecuteDataSourceByDataSourceKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataSourceByDataSourceKeyCompleted(this, new ExecuteDataSourceByDataSourceKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plexus-online.com/DataSource/GetDataSourceRequestTemplate", RequestNamespace="http://www.plexus-online.com/DataSource", ResponseNamespace="http://www.plexus-online.com/DataSource", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public GetTemplateResult GetDataSourceRequestTemplate(int dataSourceKey) {
            object[] results = this.Invoke("GetDataSourceRequestTemplate", new object[] {
                        dataSourceKey});
            return ((GetTemplateResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataSourceRequestTemplateAsync(int dataSourceKey) {
            this.GetDataSourceRequestTemplateAsync(dataSourceKey, null);
        }
        
        /// <remarks/>
        public void GetDataSourceRequestTemplateAsync(int dataSourceKey, object userState) {
            if ((this.GetDataSourceRequestTemplateOperationCompleted == null)) {
                this.GetDataSourceRequestTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataSourceRequestTemplateOperationCompleted);
            }
            this.InvokeAsync("GetDataSourceRequestTemplate", new object[] {
                        dataSourceKey}, this.GetDataSourceRequestTemplateOperationCompleted, userState);
        }
        
        private void OnGetDataSourceRequestTemplateOperationCompleted(object arg) {
            if ((this.GetDataSourceRequestTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataSourceRequestTemplateCompleted(this, new GetDataSourceRequestTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.plexus-online.com/DataSource/ExecuteDataSourcePost", RequestNamespace="http://www.plexus-online.com/DataSource", ResponseNamespace="http://www.plexus-online.com/DataSource", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ExecuteDataSourceResult ExecuteDataSourcePost(int dataSourceKey, string parameterNames, string parameterValues, string delimeter) {
            object[] results = this.Invoke("ExecuteDataSourcePost", new object[] {
                        dataSourceKey,
                        parameterNames,
                        parameterValues,
                        delimeter});
            return ((ExecuteDataSourceResult)(results[0]));
        }
        
        /// <remarks/>
        public void ExecuteDataSourcePostAsync(int dataSourceKey, string parameterNames, string parameterValues, string delimeter) {
            this.ExecuteDataSourcePostAsync(dataSourceKey, parameterNames, parameterValues, delimeter, null);
        }
        
        /// <remarks/>
        public void ExecuteDataSourcePostAsync(int dataSourceKey, string parameterNames, string parameterValues, string delimeter, object userState) {
            if ((this.ExecuteDataSourcePostOperationCompleted == null)) {
                this.ExecuteDataSourcePostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteDataSourcePostOperationCompleted);
            }
            this.InvokeAsync("ExecuteDataSourcePost", new object[] {
                        dataSourceKey,
                        parameterNames,
                        parameterValues,
                        delimeter}, this.ExecuteDataSourcePostOperationCompleted, userState);
        }
        
        private void OnExecuteDataSourcePostOperationCompleted(object arg) {
            if ((this.ExecuteDataSourcePostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteDataSourcePostCompleted(this, new ExecuteDataSourcePostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class ExecuteDataSourceRequest {
        
        private string dataSourceKeyField;
        
        private InputParameter[] inputParametersField;
        
        private string dataSourceNameField;
        
        private string dataBaseField;
        
        /// <remarks/>
        public string DataSourceKey {
            get {
                return this.dataSourceKeyField;
            }
            set {
                this.dataSourceKeyField = value;
            }
        }
        
        /// <remarks/>
        public InputParameter[] InputParameters {
            get {
                return this.inputParametersField;
            }
            set {
                this.inputParametersField = value;
            }
        }
        
        /// <remarks/>
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
            }
        }
        
        /// <remarks/>
        public string DataBase {
            get {
                return this.dataBaseField;
            }
            set {
                this.dataBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class InputParameter : Parameter {
        
        private bool requiredField;
        
        private bool outputField;
        
        private string defaultValueField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Required {
            get {
                return this.requiredField;
            }
            set {
                this.requiredField = value;
            }
        }
        
        /// <remarks/>
        public bool Output {
            get {
                return this.outputField;
            }
            set {
                this.outputField = value;
            }
        }
        
        /// <remarks/>
        public string DefaultValue {
            get {
                return this.defaultValueField;
            }
            set {
                this.defaultValueField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OutputParameter))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InputParameter))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class Parameter {
        
        private string valueField;
        
        private string nameField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class Column {
        
        private string valueField;
        
        private string nameField;
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class Row {
        
        private Column[] columnsField;
        
        /// <remarks/>
        public Column[] Columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class ResultSet {
        
        private int rowCountField;
        
        private Row[] rowsField;
        
        /// <remarks/>
        public int RowCount {
            get {
                return this.rowCountField;
            }
            set {
                this.rowCountField = value;
            }
        }
        
        /// <remarks/>
        public Row[] Rows {
            get {
                return this.rowsField;
            }
            set {
                this.rowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetTemplateResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExecuteDataSourceResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public abstract partial class BaseResult {
        
        private int statusNoField;
        
        private bool errorField;
        
        private int errorNoField;
        
        private string messageField;
        
        private string instanceNoField;
        
        /// <remarks/>
        public int StatusNo {
            get {
                return this.statusNoField;
            }
            set {
                this.statusNoField = value;
            }
        }
        
        /// <remarks/>
        public bool Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public int ErrorNo {
            get {
                return this.errorNoField;
            }
            set {
                this.errorNoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string InstanceNo {
            get {
                return this.instanceNoField;
            }
            set {
                this.instanceNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class GetTemplateResult : BaseResult {
        
        private ExecuteDataSourceRequest executeDataSourceRequestField;
        
        private ResultSet[] resultSetsField;
        
        /// <remarks/>
        public ExecuteDataSourceRequest ExecuteDataSourceRequest {
            get {
                return this.executeDataSourceRequestField;
            }
            set {
                this.executeDataSourceRequestField = value;
            }
        }
        
        /// <remarks/>
        public ResultSet[] ResultSets {
            get {
                return this.resultSetsField;
            }
            set {
                this.resultSetsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class ExecuteDataSourceResult : BaseResult {
        
        private int dataSourceKeyField;
        
        private System.Nullable<bool> quarantinedForDevelopmentField;
        
        private System.Nullable<System.DateTime> lastPrimaryDeploymentField;
        
        private System.Nullable<System.DateTime> lastTestDeploymentField;
        
        private System.Nullable<int> versionField;
        
        private string dataSourceNameField;
        
        private ResultSet[] resultSetsField;
        
        private OutputParameter[] outputParametersField;
        
        /// <remarks/>
        public int DataSourceKey {
            get {
                return this.dataSourceKeyField;
            }
            set {
                this.dataSourceKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> QuarantinedForDevelopment {
            get {
                return this.quarantinedForDevelopmentField;
            }
            set {
                this.quarantinedForDevelopmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastPrimaryDeployment {
            get {
                return this.lastPrimaryDeploymentField;
            }
            set {
                this.lastPrimaryDeploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastTestDeployment {
            get {
                return this.lastTestDeploymentField;
            }
            set {
                this.lastTestDeploymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string DataSourceName {
            get {
                return this.dataSourceNameField;
            }
            set {
                this.dataSourceNameField = value;
            }
        }
        
        /// <remarks/>
        public ResultSet[] ResultSets {
            get {
                return this.resultSetsField;
            }
            set {
                this.resultSetsField = value;
            }
        }
        
        /// <remarks/>
        public OutputParameter[] OutputParameters {
            get {
                return this.outputParametersField;
            }
            set {
                this.outputParametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.plexus-online.com/DataSource")]
    public partial class OutputParameter : Parameter {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteDataSourceCompletedEventHandler(object sender, ExecuteDataSourceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataSourceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataSourceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExecuteDataSourceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExecuteDataSourceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteDataSourceByDataSourceKeyCompletedEventHandler(object sender, ExecuteDataSourceByDataSourceKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataSourceByDataSourceKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataSourceByDataSourceKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExecuteDataSourceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExecuteDataSourceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDataSourceRequestTemplateCompletedEventHandler(object sender, GetDataSourceRequestTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataSourceRequestTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataSourceRequestTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetTemplateResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetTemplateResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void ExecuteDataSourcePostCompletedEventHandler(object sender, ExecuteDataSourcePostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteDataSourcePostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteDataSourcePostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExecuteDataSourceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExecuteDataSourceResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591